apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
spec:
  project: platform
  source:
    repoURL: git@github.com:loudsquelch/test-code-owners.git
    targetRevision: main
    path: applications/app1/overlays/prod
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated: {}
